#!/bin/bash

# ============================================================
# Konnect SVN Automation - Setup Script
# Production deployment script for SVN hosting automation
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Konnect SVN Automation Setup${NC}"
echo -e "${GREEN}========================================${NC}"
echo

# ============================================================
# 1. Check prerequisites
# ============================================================
echo -e "${YELLOW}[1/7] Checking prerequisites...${NC}"

check_command() {
  if ! command -v "$1" &> /dev/null; then
    echo -e "${RED}✗ $1 is not installed${NC}"
    exit 1
  fi
  echo -e "${GREEN}✓ $1 found${NC}"
}

check_command "svnadmin"
check_command "apache2ctl"
check_command "htpasswd"
check_command "postgresql"
echo

# ============================================================
# 2. Verify environment variables
# ============================================================
echo -e "${YELLOW}[2/7] Verifying environment variables...${NC}"

required_vars=(
  "SVN_REPOS_ROOT"
  "HTPASSWD_PATH"
  "AUTHZ_PATH"
  "DB_HOST"
  "DB_NAME"
  "DB_USER"
  "APACHE_RELOAD_CMD"
)

for var in "${required_vars[@]}"; do
  if [ -z "${!var}" ]; then
    echo -e "${RED}✗ $var not set in .env${NC}"
    exit 1
  fi
  echo -e "${GREEN}✓ $var: ${!var}${NC}"
done
echo

# ============================================================
# 3. Create SVN repository root if needed
# ============================================================
echo -e "${YELLOW}[3/7] Setting up SVN repository root...${NC}"

SVN_ROOT="${SVN_REPOS_ROOT}"
if [ ! -d "$SVN_ROOT" ]; then
  echo "Creating directory: $SVN_ROOT"
  sudo mkdir -p "$SVN_ROOT"
  sudo chown www-data:www-data "$SVN_ROOT"
  sudo chmod 770 "$SVN_ROOT"
  echo -e "${GREEN}✓ Created $SVN_ROOT${NC}"
else
  echo -e "${GREEN}✓ $SVN_ROOT exists${NC}"
fi
echo

# ============================================================
# 4. Initialize htpasswd and authz files
# ============================================================
echo -e "${YELLOW}[4/7] Initializing htpasswd and authz files...${NC}"

# Create empty htpasswd if it doesn't exist
if [ ! -f "$HTPASSWD_PATH" ]; then
  echo "Creating htpasswd file: $HTPASSWD_PATH"
  echo "# Generated by Konnect SVN Automation" | sudo tee "$HTPASSWD_PATH" > /dev/null
  sudo chmod 640 "$HTPASSWD_PATH"
  sudo chown www-data:www-data "$HTPASSWD_PATH"
  echo -e "${GREEN}✓ Created $HTPASSWD_PATH${NC}"
else
  echo -e "${GREEN}✓ $HTPASSWD_PATH exists${NC}"
fi

# Create empty authz if it doesn't exist
if [ ! -f "$AUTHZ_PATH" ]; then
  echo "Creating authz file: $AUTHZ_PATH"
  echo "# Generated by Konnect SVN Automation" | sudo tee "$AUTHZ_PATH" > /dev/null
  sudo chmod 640 "$AUTHZ_PATH"
  sudo chown www-data:www-data "$AUTHZ_PATH"
  echo -e "${GREEN}✓ Created $AUTHZ_PATH${NC}"
else
  echo -e "${GREEN}✓ $AUTHZ_PATH exists${NC}"
fi
echo

# ============================================================
# 5. Create Apache reload wrapper script
# ============================================================
echo -e "${YELLOW}[5/7] Setting up Apache reload wrapper...${NC}"

RELOAD_SCRIPT="/usr/local/sbin/konnect-apache-reload"

cat > /tmp/konnect-apache-reload.sh << 'EOF'
#!/bin/bash
# Apache reload wrapper for Konnect SVN Automation
# Validates configuration before reloading

set -e

# Validate syntax
if ! apache2ctl configtest > /dev/null 2>&1; then
  echo "Apache configuration test failed"
  exit 1
fi

# Graceful reload (existing connections continue)
systemctl reload apache2

exit 0
EOF

chmod 755 /tmp/konnect-apache-reload.sh
sudo mv /tmp/konnect-apache-reload.sh "$RELOAD_SCRIPT"
echo -e "${GREEN}✓ Created $RELOAD_SCRIPT${NC}"
echo

# ============================================================
# 6. Configure sudoers for konnect user
# ============================================================
echo -e "${YELLOW}[6/7] Configuring sudoers...${NC}"

SUDOERS_FILE="/etc/sudoers.d/konnect-svn"

# Check if konnect user exists, if not create it
if ! id -u konnect > /dev/null 2>&1; then
  echo "Creating konnect user..."
  sudo useradd -r -s /bin/bash -d /var/lib/konnect konnect
  echo -e "${GREEN}✓ Created konnect user${NC}"
else
  echo -e "${GREEN}✓ konnect user exists${NC}"
fi

# Create sudoers configuration
cat > /tmp/konnect-svn-sudoers << 'EOF'
# Konnect SVN Automation sudoers configuration
# NEVER edit this file directly - use visudo

# Allow konnect user specific commands without password
Defaults:konnect !requiretty

# htpasswd management
konnect ALL=(ALL) NOPASSWD: /usr/bin/htpasswd

# Apache reload wrapper
konnect ALL=(ALL) NOPASSWD: /usr/local/sbin/konnect-apache-reload

# Apache2ctl (for config test)
konnect ALL=(ALL) NOPASSWD: /usr/sbin/apache2ctl

# SVN admin commands
konnect ALL=(ALL) NOPASSWD: /usr/bin/svnadmin

# chown and chmod for repo setup
konnect ALL=(ALL) NOPASSWD: /bin/chown
konnect ALL=(ALL) NOPASSWD: /bin/chmod
konnect ALL=(ALL) NOPASSWD: /bin/mkdir

# Deny everything else
konnect ALL = (ALL) DENY
EOF

# Validate and install sudoers
if sudo visudo -c -f /tmp/konnect-svn-sudoers > /dev/null 2>&1; then
  sudo mv /tmp/konnect-svn-sudoers "$SUDOERS_FILE"
  sudo chmod 440 "$SUDOERS_FILE"
  echo -e "${GREEN}✓ Installed sudoers configuration${NC}"
else
  echo -e "${RED}✗ Sudoers validation failed${NC}"
  exit 1
fi
echo

# ============================================================
# 7. Create lock directories
# ============================================================
echo -e "${YELLOW}[7/7] Setting up lock directories...${NC}"

LOCK_DIR="/var/lock/konnect"
if [ ! -d "$LOCK_DIR" ]; then
  sudo mkdir -p "$LOCK_DIR"
  sudo chown konnect:konnect "$LOCK_DIR"
  sudo chmod 755 "$LOCK_DIR"
  echo -e "${GREEN}✓ Created lock directory: $LOCK_DIR${NC}"
else
  echo -e "${GREEN}✓ Lock directory exists${NC}"
fi
echo

# ============================================================
# Summary
# ============================================================
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Update your Apache configuration to use:"
echo "   - AuthUserFile: $HTPASSWD_PATH"
echo "   - AuthzSVNAccessFile: $AUTHZ_PATH"
echo "2. Run: npm run migrate (to create SVN tables)"
echo "3. Restart Konnect: pm2 restart konnect"
echo
echo -e "${GREEN}SVN Automation is ready!${NC}"
