'use strict';

const fse       = require('fs-extra');
const dayjs     = require('dayjs');

const apacheCfg = require('../config/apache');

// ❌ REMOVE THIS
// const { applyApacheConfig } = require('./apacheService');

// ✅ ADD THIS
const { reloadApache } = require('./apacheService');

const logger    = require('../config/logger');

/**
 * Rebuild the authz file from DB state and safely reload Apache.
 */
async function rebuildAuthzFile(db) {
  const authzPath = apacheCfg.authzPath;

  try {

    logger.info('🔄 Starting authz rebuild...');

    // ── 1. Load groups ─────────────────────────────
    const { rows: groups } = await db.query(`
      SELECT g.name,
      COALESCE(string_agg(u.username, ', ' ORDER BY u.username), '') AS members
      FROM groups g
      LEFT JOIN group_members gm ON gm.group_id = g.id
      LEFT JOIN users u ON u.id = gm.user_id
      GROUP BY g.name
      ORDER BY g.name
    `);

    // ── 2. Load permissions ────────────────────────
    const { rows: perms } = await db.query(`
      SELECT
        r.name AS repo_name,
        p.path,
        p.subject_type,
        p.permission,
        CASE p.subject_type
          WHEN 'user' THEN u.username
          WHEN 'group' THEN g2.name
        END AS subject_name
      FROM permissions p
      JOIN repositories r ON r.id = p.repo_id
      LEFT JOIN users u ON p.subject_type = 'user' AND u.id = p.subject_id
      LEFT JOIN groups g2 ON p.subject_type = 'group' AND g2.id = p.subject_id
      ORDER BY r.name, p.path, p.subject_type, subject_name
    `);

    // ── 3. Build authz content ─────────────────────
    const lines = [
      `### GENERATED BY SVNBRIDGE — DO NOT EDIT ###`,
      `### Updated: ${dayjs().format('YYYY-MM-DD HH:mm:ss')} ###`,
      '',
      '[groups]',
    ];

    for (const g of groups) {
      lines.push(`${g.name} = ${g.members}`);
    }

    // Group permissions by repo:path
    const sections = {};

    for (const p of perms) {
      const key = `${p.repo_name}:${p.path}`;

      if (!sections[key]) sections[key] = [];

      const subject = p.subject_type === 'group'
        ? `@${p.subject_name}`
        : p.subject_name;

      sections[key].push(`${subject} = ${p.permission}`);
    }

    // Default deny
    lines.push('', '[/]', '* =');

    for (const [section, entries] of Object.entries(sections)) {
      lines.push('', `[${section}]`, ...entries);
    }

    const content = lines.join('\n') + '\n';

    // ── 4. Atomic write (SAFE) ─────────────────────
    const tmpPath = authzPath + '.tmp';

    await fse.ensureFile(authzPath);
    await fse.writeFile(tmpPath, content, 'utf8');
    await fse.move(tmpPath, authzPath, { overwrite: true });

    logger.info(`✅ authz file rebuilt: ${authzPath}`);

    // ── 5. 🔥 FIXED: ONLY RELOAD APACHE ───────────
    try {
      await reloadApache(); // ✅ FIX APPLIED
      logger.info('✅ Apache reloaded successfully');
    } catch (err) {
      logger.error('⚠️ Apache reload failed:', err.message);
      // ❗ DO NOT throw → prevents API crash
    }

    return content;

  } catch (error) {

    logger.error('❌ Failed to rebuild authz file:', error.message);

    throw error;
  }
}

/**
 * Get current authz file content
 */
async function getAuthzContent() {
  try {
    return await fse.readFile(apacheCfg.authzPath, 'utf8');
  } catch {
    return '';
  }
}

module.exports = {
  rebuildAuthzFile,
  getAuthzContent
};