// authzService.js
'use strict';

const fse         = require('fs-extra');
const dayjs       = require('dayjs');
const apacheCfg   = require('../config/apache');
const apacheSvc   = require('./apacheService');
const logger      = require('../config/logger');

/**
 * Rebuild the authz file from DB state and reload Apache.
 *
 * authz format:
 *   [groups]
 *   devs = alice, bob
 *
 *   [repo-name:/path]
 *   @devs = rw
 *   alice = r
 */
async function rebuildAuthzFile(db) {
  const authzPath = apacheCfg.authzPath;

  // ── 1. Load groups + members ──────────────────────────────────────────────
  const { rows: groups } = await db.query(
    `SELECT g.name, COALESCE(string_agg(u.username, ', ' ORDER BY u.username), '') AS members
     FROM groups g
     LEFT JOIN group_members gm ON gm.group_id = g.id
     LEFT JOIN users u          ON u.id = gm.user_id
     GROUP BY g.name
     ORDER BY g.name`
  );

  // ── 2. Load permissions ───────────────────────────────────────────────────
  const { rows: perms } = await db.query(
    `SELECT
       r.name          AS repo_name,
       p.path,
       p.subject_type,
       p.permission,
       CASE p.subject_type
         WHEN 'user'  THEN u.username
         WHEN 'group' THEN g2.name
       END AS subject_name
     FROM permissions p
     JOIN repositories r ON r.id = p.repo_id
     LEFT JOIN users  u  ON p.subject_type = 'user'  AND u.id  = p.subject_id
     LEFT JOIN groups g2 ON p.subject_type = 'group' AND g2.id = p.subject_id
     ORDER BY r.name, p.path, p.subject_type, subject_name`
  );

  // ── 3. Build [groups] section ─────────────────────────────────────────────
  const lines = [
    `### GENERATED BY SVNBRIDGE — DO NOT EDIT MANUALLY ###`,
    `### Last updated: ${dayjs().format('YYYY-MM-DD HH:mm:ss')} ###`,
    '',
    '[groups]',
  ];

  for (const g of groups) {
    lines.push(`${g.name} = ${g.members}`);
  }

  // ── 4. Build [repo:/path] sections ───────────────────────────────────────
  // Group perms by (repo, path)
  const sections = {};
  for (const p of perms) {
    const key = `${p.repo_name}:${p.path}`;
    if (!sections[key]) sections[key] = [];
    const subject = p.subject_type === 'group' ? `@${p.subject_name}` : p.subject_name;
    sections[key].push(`${subject} = ${p.permission}`);
  }

  lines.push('', '[/]', '* =');  // Global deny by default

  for (const [section, entries] of Object.entries(sections)) {
    lines.push('', `[${section}]`, ...entries);
  }

  // ── 5. Write atomically ───────────────────────────────────────────────────
  const content = lines.join('\n') + '\n';
  const tmp = authzPath + '.tmp';
  await fse.ensureFile(authzPath);
  await fse.writeFile(tmp, content, 'utf8');
  await fse.move(tmp, authzPath, { overwrite: true });

  logger.info(`authz file rebuilt: ${authzPath}`);

  // ── 6. Reload Apache ──────────────────────────────────────────────────────
  await apacheSvc.reloadApache();

  return content;
}

/**
 * Return current authz file contents as a string.
 */
async function getAuthzContent() {
  try {
    return await fse.readFile(apacheCfg.authzPath, 'utf8');
  } catch {
    return '';
  }
}

module.exports = { rebuildAuthzFile, getAuthzContent };
