const fs = require('fs').promises;
const path = require('path');
const crypto = require('crypto');
const { execFile } = require('child_process');
const { promisify } = require('util');
const { v4: uuidv4 } = require('uuid');
const db = require('../config/database');
const logger = require('../config/logger');
const env = require('../config/env');
const { DistributedLock, LOCK_TYPES } = require('./svnLockingService');

const execFileAsync = promisify(execFile);

class AuthzGenerationEngine {
  constructor() {
    this.authzPath = env.AUTHZ_PATH;
    this.authzBackupPath = `${env.AUTHZ_PATH}.prev`;
    this.authzTmpDir = '/tmp';
  }

  /**
   * Generate full authz file from database state
   * This is the main entry point - acquires lock, generates, validates, deploys, reloads
   */
  async generateFullAuthz(triggeredBy = null) {
    const generationId = uuidv4();
    const startTime = new Date();
    const lock = new DistributedLock(LOCK_TYPES.AUTHZ_GENERATION);

    logger.info('Starting authz generation', { generationId, triggeredBy });

    // Record as pending
    await this.recordGenerationStart(generationId, triggeredBy);

    try {
      // Acquire distributed lock
      await lock.acquire(5000, 600000);

      // Backup current authz
      try {
        await fs.copyFile(this.authzPath, this.authzBackupPath);
        logger.debug('Backed up current authz file', { backupPath: this.authzBackupPath });
      } catch (error) {
        // OK if backup doesn't exist (first time)
        if (error.code !== 'ENOENT') throw error;
      }

      // Query all repositories with their permissions
      const repos = await this.getRepositoriesWithPermissions();
      logger.debug('Fetched repositories', { count: repos.length });

      // Generate authz content
      const authzContent = this.buildAuthzContent(repos);
      logger.debug('Generated authz content', { length: authzContent.length });

      // Calculate hash
      const hash = crypto.createHash('sha256').update(authzContent).digest('hex');

      // Validate syntax
      await this.validateAuthzSyntax(authzContent);
      logger.debug('Authz syntax validated');

      // Deploy atomically (temp file + rename)
      const tmpFile = await this.deployAuthzFile(authzContent);
      logger.info('Authz file deployed', { tmpFile });

      // Test Apache configuration
      await this.testApacheConfig();
      logger.debug('Apache config validated');

      // Reload Apache gracefully
      await this.reloadApache();
      logger.info('Apache reloaded successfully');

      // Record success
      const affectedRepos = repos.map(r => r.repository_id);
      await this.recordGenerationSuccess(generationId, hash, affectedRepos, startTime);

      logger.info('Authz generation completed', { generationId, hash, repos: affectedRepos.length });

      return {
        success: true,
        generationId,
        hash,
        affectedRepos,
        generatedAt: new Date(),
        durationMs: Date.now() - startTime.getTime()
      };

    } catch (error) {
      logger.error('Authz generation failed', { generationId, error: error.message });

      // Try to rollback
      try {
        await this.rollbackAuthz();
        await this.reloadApache();
        logger.info('Authz rolled back successfully');
      } catch (rollbackError) {
        logger.error('Authz rollback FAILED - manual intervention needed', { rollbackError });
      }

      // Record failure
      await this.recordGenerationFailure(generationId, error.message, startTime);

      throw error;

    } finally {
      await lock.release();
    }
  }

  /**
   * Fetch all active repositories with their permissions
   */
  async getRepositoriesWithPermissions() {
    const query = `
      SELECT
        sr.repository_id,
        r.name AS repo_name,
        sr.svn_path,
        sr.owner_id,
        json_agg(
          json_build_object(
            'path_pattern', sp.path_pattern,
            'subject_type', sp.subject_type,
            'subject_id', sp.subject_id,
            'access_level', sp.access_level
          ) ORDER BY sp.path_pattern
        ) FILTER (WHERE sp.id IS NOT NULL) AS permissions
      FROM svn_repositories sr
      JOIN repositories r ON r.id = sr.repository_id
      LEFT JOIN svn_permissions sp ON sp.repository_id = r.id
      WHERE sr.is_initialized = true AND r.is_active = true
      GROUP BY sr.repository_id, r.name, sr.svn_path, sr.owner_id
      ORDER BY r.name
    `;

    const result = await db.query(query);
    return result.rows;
  }

  /**
   * Build authz content from repository permissions
   */
  buildAuthzContent(repos) {
    let content = '# Generated by Konnect SVN Automation\n';
    content += `# Generated at: ${new Date().toISOString()}\n`;
    content += '# DO NOT EDIT MANUALLY - Changes will be overwritten\n\n';

    for (const repo of repos) {
      const permissions = (repo.permissions || [])
        .filter(p => p.access_level !== 'none');

      // Group by path pattern
      const pathGroups = {};
      for (const perm of permissions) {
        if (!pathGroups[perm.path_pattern]) {
          pathGroups[perm.path_pattern] = [];
        }
        pathGroups[perm.path_pattern].push(perm);
      }

      // Generate sections for each path
      for (const [pathPattern, pathPerms] of Object.entries(pathGroups)) {
        const section = this.buildAuthzSection(repo.repo_name, pathPattern, pathPerms);
        content += section + '\n';
      }

      // Add root deny for anonymous (if not already present)
      const hasRootSection = Object.keys(pathGroups).includes('/');
      if (!hasRootSection) {
        content += `[${repo.repo_name}:/]\n_anonymous_=\n\n`;
      }
    }

    return content;
  }

  /**
   * Build single authz section [repo:path]
   */
  buildAuthzSection(repoName, pathPattern, permissions) {
    let section = `[${repoName}:${pathPattern}]\n`;

    // Sort permissions by subject for deterministic output
    const sortedPerms = permissions.sort((a, b) =>
      `${a.subject_type}:${a.subject_id}`.localeCompare(
        `${b.subject_type}:${b.subject_id}`
      )
    );

    // Add each permission
    for (const perm of sortedPerms) {
      const subject = this.formatAuthzSubject(perm);
      const access = this.formatAuthzAccess(perm.access_level);
      section += `${subject}=${access}\n`;
    }

    // Always explicitly deny anonymous
    if (!sortedPerms.some(p => p.subject_type === '_anonymous_')) {
      section += '_anonymous_=\n';
    }

    return section;
  }

  /**
   * Format authz subject (user, group, or _anonymous_)
   */
  formatAuthzSubject(permission) {
    switch (permission.subject_type) {
      case 'user':
        return `user_${permission.subject_id}`;
      case 'group':
        return `@group_${permission.subject_id}`;
      case '_anonymous_':
        return '_anonymous_';
      default:
        throw new Error(`Unknown subject type: ${permission.subject_type}`);
    }
  }

  /**
   * Format authz access level (read-only or read-write)
   */
  formatAuthzAccess(accessLevel) {
    switch (accessLevel) {
      case 'read-only':
        return 'r';
      case 'read-write':
        return 'rw';
      case 'none':
        return '';
      default:
        throw new Error(`Unknown access level: ${accessLevel}`);
    }
  }

  /**
   * Validate authz syntax by attempting to parse with svnlook
   */
  async validateAuthzSyntax(content) {
    try {
      // Write to temp file
      const tmpFile = path.join(this.authzTmpDir, `authz-validate-${Date.now()}`);
      await fs.writeFile(tmpFile, content, { mode: 0o600 });

      try {
        // Validate with svnlook - check if it can read the file
        // This is a basic validation; full validation requires a valid SVN repo
        logger.debug('Validating authz syntax', { tmpFile });
        // For now, just check basic format - could expand to full parse if needed
        this.validateAuthzFormat(content);
      } finally {
        try {
          await fs.unlink(tmpFile);
        } catch {
          // ignore
        }
      }

    } catch (error) {
      throw new Error(`Authz syntax validation failed: ${error.message}`);
    }
  }

  /**
   * Basic authz format validation
   */
  validateAuthzFormat(content) {
    const lines = content.split('\n');
    const sectionRegex = /^\[.*:.*\]$/;
    const ruleRegex = /^([a-zA-Z0-9_@-]+)=(r|rw)?$/;

    let currentSection = null;
    for (const line of lines) {
      const trimmed = line.trim();

      // Skip comments and empty lines
      if (!trimmed || trimmed.startsWith('#')) continue;

      // Check section
      if (sectionRegex.test(trimmed)) {
        currentSection = trimmed;
        continue;
      }

      // Check rule (only if we're in a section)
      if (currentSection && !ruleRegex.test(trimmed)) {
        throw new Error(`Invalid authz rule in ${currentSection}: ${trimmed}`);
      }
    }
  }

  /**
   * Deploy authz file atomically (temp file + rename)
   */
  async deployAuthzFile(content) {
    const tmpFile = path.join(this.authzTmpDir, `.authz.tmp.${uuidv4()}`);

    try {
      // Apache runs as www-data and must be able to read this file.
      await fs.writeFile(tmpFile, content, {
        mode: 0o644,
        flag: 'w'
      });

      logger.debug('Wrote temp authz file', { tmpFile });

      // Atomic rename
      await fs.rename(tmpFile, this.authzPath);
      logger.debug('Renamed temp file to live authz', { tmpFile, authzPath: this.authzPath });

      return tmpFile;

    } catch (error) {
      // Cleanup temp file on error
      try {
        await fs.unlink(tmpFile);
      } catch {
        // ignore
      }
      throw error;
    }
  }

  /**
   * Test Apache configuration (dry-run)
   */
  async testApacheConfig() {
    try {
      // apache2ctl configtest writes "Syntax OK" to STDERR, not stdout
      const { stdout, stderr } = await execFileAsync('/usr/sbin/apache2ctl', ['configtest'], {
        timeout: 10000
      });

      const combined = (stdout + ' ' + stderr).toLowerCase();
      if (!combined.includes('syntax ok')) {
        throw new Error(`Apache config test failed: ${stdout} ${stderr}`);
      }

      logger.debug('Apache config test passed');
    } catch (error) {
      // execFile rejects on non-zero exit code; stderr may still contain "Syntax OK"
      // apache2ctl configtest exits 0 on success, non-zero on failure
      const combined = ((error.stdout || '') + ' ' + (error.stderr || '')).toLowerCase();
      if (combined.includes('syntax ok')) {
        // Config is actually fine — apache2ctl just printed warnings to stderr
        logger.debug('Apache config test passed (warnings present)');
        return;
      }
      throw new Error(`Apache config validation failed: ${error.message}`);
    }
  }

  /**
   * Reload Apache gracefully
   */
  async reloadApache() {
    try {
      const reloadCmd = env.APACHE_RELOAD_CMD || 'sudo systemctl reload apache2';

      // execFile requires separate binary + args array (not a single string)
      // Split on whitespace: "sudo systemctl reload apache2" → ['sudo', 'systemctl', 'reload', 'apache2']
      const parts = reloadCmd.trim().split(/\s+/);
      const bin   = parts[0];
      const args  = parts.slice(1);

      const { stdout, stderr } = await execFileAsync(bin, args, {
        timeout: 15000
      });

      logger.info('Apache reload succeeded', { output: stdout || stderr });
    } catch (error) {
      throw new Error(`Apache reload failed: ${error.message}`);
    }
  }

  /**
   * Rollback authz to previous version
   */
  async rollbackAuthz() {
    try {
      const backupExists = await this.fileExists(this.authzBackupPath);
      if (!backupExists) {
        logger.warn('No backup authz file found for rollback');
        return;
      }

      await fs.copyFile(this.authzBackupPath, this.authzPath);
      logger.info('Authz rolled back from backup');
    } catch (error) {
      throw new Error(`Rollback failed: ${error.message}`);
    }
  }

  /**
   * Helper: Check if file exists
   */
  async fileExists(filePath) {
    try {
      await fs.access(filePath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Record generation start
   */
  async recordGenerationStart(generationId, triggeredBy) {
    await db.query(
      `INSERT INTO authz_generation_history
       (generation_id, started_at, status, triggered_by)
       VALUES ($1, $2, 'pending', $3)`,
      [generationId, new Date(), triggeredBy]
    );
  }

  /**
   * Record generation success
   */
  async recordGenerationSuccess(generationId, hash, affectedRepos, startTime) {
    await db.query(
      `UPDATE authz_generation_history
       SET status = 'success', completed_at = $1, authz_hash = $2, affected_repos = $3
       WHERE generation_id = $4`,
      [new Date(), hash, affectedRepos, generationId]
    );
  }

  /**
   * Record generation failure
   */
  async recordGenerationFailure(generationId, errorMessage, startTime) {
    await db.query(
      `UPDATE authz_generation_history
       SET status = 'failed', completed_at = $1, error_message = $2
       WHERE generation_id = $3`,
      [new Date(), errorMessage, generationId]
    );
  }
}

module.exports = new AuthzGenerationEngine();
