const fs = require('fs').promises;
const path = require('path');
const crypto = require('crypto');
const { v4: uuidv4 } = require('uuid');
const db = require('../config/database');
const logger = require('../config/logger');
const env = require('../config/env');

class HtpasswdSyncEngine {
  constructor() {
    this.htpasswdPath = env.HTPASSWD_PATH;
    this.lockPath = '/var/lock/konnect-htpasswd.lock';
  }

  /**
   * Generate Apache {SHA} password hash
   * Apache {SHA} format = "{SHA}" + base64(SHA1(password))
   * No salt — matches htpasswd -s output and what Apache/mod_dav_svn validates.
   * IMPORTANT: Must be identical to svnManagementService.generateApacheMD5
   * so the hash stored in svn_users.password_hash_md5 is valid when written
   * to the htpasswd file.
   */
  generateApacheMD5(password) {
    const hash = crypto.createHash('sha1').update(password).digest();
    return '{SHA}' + hash.toString('base64');
  }

  /**
   * Sync htpasswd file from database state
   */
  async syncHtpasswdFile(triggeredBy = null) {
    const syncId = uuidv4();
    const startTime = new Date();

    logger.info('Starting htpasswd sync', { syncId, triggeredBy });

    try {
      // Acquire file lock
      await this.acquireFileLock();

      try {
        // Fetch SVN users from database
        const users = await this.getSvnUsersForSync();
        logger.debug('Fetched SVN users', { count: users.length });

        // Generate htpasswd content
        const content = this.buildHtpasswdContent(users);

        // Validate before writing
        const validation = this.validateHtpasswdContent(content, users);
        if (!validation.valid) {
          throw new Error(`Validation failed: ${validation.errors.join(', ')}`);
        }

        // Deploy atomically
        await this.deployHtpasswdFile(content);
        logger.info('Htpasswd file deployed', { syncId });

        // Record success
        await this.recordSyncSuccess(syncId, users.length, startTime, triggeredBy);

        logger.info('Htpasswd sync completed', { syncId, userCount: users.length });

        return {
          success: true,
          syncId,
          usersSynced: users.length,
          syncedAt: new Date(),
          durationMs: Date.now() - startTime.getTime()
        };

      } finally {
        await this.releaseFileLock();
      }

    } catch (error) {
      logger.error('Htpasswd sync failed', { syncId, error: error.message });
      await this.recordSyncFailure(syncId, error.message, startTime, triggeredBy);
      throw error;
    }
  }

  /**
   * Get all SVN-enabled users from database
   */
  async getSvnUsersForSync() {
    const query = `
      SELECT
        su.user_id,
        u.username,
        su.svn_username,
        su.password_hash_md5
      FROM svn_users su
      JOIN users u ON u.id = su.user_id
      WHERE su.is_svn_enabled = true
        AND u.is_active = true
      ORDER BY su.svn_username
    `;

    const result = await db.query(query);
    return result.rows;
  }

  /**
   * Build htpasswd content from user list
   * Format: username:password_hash
   */
  buildHtpasswdContent(users) {
    let content = '# Generated by Konnect SVN Automation\n';
    content += `# Generated at: ${new Date().toISOString()}\n`;
    content += '# DO NOT EDIT MANUALLY - Changes will be overwritten\n\n';

    for (const user of users) {
      // Ensure password_hash_md5 is valid
      if (!user.password_hash_md5) {
        logger.warn('User missing password hash', { user: user.svn_username });
        continue;
      }

      // Format: username:hash
      content += `${user.svn_username}:${user.password_hash_md5}\n`;
    }

    return content;
  }

  /**
   * Validate htpasswd content structure
   */
  validateHtpasswdContent(content, expectedUsers) {
    const errors = [];

    // Parse content
    const lines = content.split('\n');
    const parsedUsers = {};

    for (const line of lines) {
      const trimmed = line.trim();

      // Skip comments and empty lines
      if (!trimmed || trimmed.startsWith('#')) continue;

      // Parse username:hash format
      const parts = trimmed.split(':');
      if (parts.length !== 2) {
        errors.push(`Invalid format: ${trimmed}`);
        continue;
      }

      const [username, hash] = parts;
      if (!username || !hash) {
        errors.push(`Missing username or hash: ${trimmed}`);
        continue;
      }

      parsedUsers[username] = hash;
    }

    // Check all expected users are present
    for (const user of expectedUsers) {
      if (!parsedUsers[user.svn_username]) {
        errors.push(`Missing user: ${user.svn_username}`);
      }
    }

    // Check for unexpected users (unless explicitly allowed)
    const expectedUsernames = new Set(expectedUsers.map(u => u.svn_username));
    for (const username of Object.keys(parsedUsers)) {
      if (!expectedUsernames.has(username)) {
        logger.warn(`Unexpected user in generated content: ${username}`);
        // Don't fail - just warn
      }
    }

    return {
      valid: errors.length === 0,
      errors
    };
  }

  /**
   * Deploy htpasswd file atomically
   */
  async deployHtpasswdFile(content) {
    const tmpFile = path.join('/tmp', `.passwd.tmp.${uuidv4()}`);

    try {
      // Apache runs as www-data and must be able to read this file.
      await fs.writeFile(tmpFile, content, {
        mode: 0o644,
        flag: 'w'
      });

      logger.debug('Wrote temp htpasswd file', { tmpFile });

      // Atomic rename
      await fs.rename(tmpFile, this.htpasswdPath);
      logger.debug('Renamed temp file to live htpasswd', { tmpFile, htpasswdPath: this.htpasswdPath });

      // Verify permissions
      await fs.chmod(this.htpasswdPath, 0o644);

    } catch (error) {
      // Cleanup temp file on error
      try {
        await fs.unlink(tmpFile);
      } catch {
        // ignore
      }
      throw error;
    }
  }

  /**
   * Acquire file lock with timeout
   */
  async acquireFileLock(timeout = 5000, maxRetries = 10) {
    const startTime = Date.now();
    let retries = 0;
    let retryDelay = 50;

    while (retries < maxRetries && Date.now() - startTime < timeout) {
      try {
        // Try to create lock file (fails if exists)
        const lockHandle = await fs.open(this.lockPath, 'wx');
        await lockHandle.write(`locked at ${new Date().toISOString()}`);
        await lockHandle.close();

        logger.debug('File lock acquired', { lockPath: this.lockPath });
        return true;

      } catch (error) {
        if (error.code === 'EEXIST') {
          // Lock file exists - check if it's stale
          try {
            const stats = await fs.stat(this.lockPath);
            const ageMs = Date.now() - stats.mtimeMs;

            // If lock is older than 5 minutes, consider it stale
            if (ageMs > 300000) {
              logger.warn('Removing stale lock file', { age: ageMs });
              await fs.unlink(this.lockPath);
              continue;
            }

          } catch {
            // ignore stat error
          }

          // Wait and retry
          retries++;
          await new Promise(resolve => setTimeout(resolve, retryDelay));
          retryDelay = Math.min(retryDelay * 2, 1000);
          continue;
        }

        throw error;
      }
    }

    throw new Error(`Failed to acquire htpasswd lock after ${timeout}ms`);
  }

  /**
   * Release file lock
   */
  async releaseFileLock() {
    try {
      await fs.unlink(this.lockPath);
      logger.debug('File lock released', { lockPath: this.lockPath });
    } catch (error) {
      if (error.code !== 'ENOENT') {
        logger.error('Error releasing file lock', { error });
      }
    }
  }

  /**
   * Record sync success in database
   */
  async recordSyncSuccess(syncId, userCount, startTime, triggeredBy) {
    await db.query(
      `INSERT INTO htpasswd_sync_history
       (sync_id, started_at, completed_at, status, users_synced, triggered_by)
       VALUES ($1, $2, $3, 'success', $4, $5)`,
      [syncId, startTime, new Date(), userCount, triggeredBy]
    );
  }

  /**
   * Record sync failure in database
   */
  async recordSyncFailure(syncId, errorMessage, startTime, triggeredBy) {
    await db.query(
      `INSERT INTO htpasswd_sync_history
       (sync_id, started_at, completed_at, status, error_message, triggered_by)
       VALUES ($1, $2, $3, 'failed', $4, $5)`,
      [syncId, startTime, new Date(), errorMessage, triggeredBy]
    );
  }

  /**
   * Sync single user's password to htpasswd
   * Used when user password changes
   */
  async syncUserPassword(userId) {
    try {
      const result = await db.query(
        `SELECT su.svn_username, su.password_hash_md5
         FROM svn_users su
         WHERE su.user_id = $1 AND su.is_svn_enabled = true`,
        [userId]
      );

      if (result.rows.length === 0) {
        logger.warn('User not found or SVN not enabled', { userId });
        return false;
      }

      // Full resync is safer than individual updates
      // (avoids potential race conditions)
      await this.syncHtpasswdFile(userId);
      return true;

    } catch (error) {
      logger.error('Failed to sync user password', { userId, error });
      throw error;
    }
  }
}

module.exports = new HtpasswdSyncEngine();
