const htpasswdSyncEngine = require('../services/htpasswdSyncEngine');

describe('HtpasswdSyncEngine', () => {
  describe('buildHtpasswdContent', () => {
    it('should generate htpasswd content from users', () => {
      const users = [
        { svn_username: 'alice', password_hash_md5: '{SHA}hash1' },
        { svn_username: 'bob', password_hash_md5: '{SHA}hash2' }
      ];

      const content = htpasswdSyncEngine.buildHtpasswdContent(users);

      expect(content).toContain('alice:{SHA}hash1');
      expect(content).toContain('bob:{SHA}hash2');
      expect(content).toContain('Generated by Konnect');
    });

    it('should sort users alphabetically', () => {
      const users = [
        { svn_username: 'charlie', password_hash_md5: '{SHA}hash3' },
        { svn_username: 'alice', password_hash_md5: '{SHA}hash1' },
        { svn_username: 'bob', password_hash_md5: '{SHA}hash2' }
      ];

      const content = htpasswdSyncEngine.buildHtpasswdContent(users);
      const lines = content.split('\n').filter(l => l && !l.startsWith('#'));

      expect(lines[0]).toBe('alice:{SHA}hash1');
      expect(lines[1]).toBe('bob:{SHA}hash2');
      expect(lines[2]).toBe('charlie:{SHA}hash3');
    });

    it('should skip users without password hashes', () => {
      const users = [
        { svn_username: 'alice', password_hash_md5: '{SHA}hash1' },
        { svn_username: 'bob', password_hash_md5: null },
        { svn_username: 'charlie', password_hash_md5: '{SHA}hash3' }
      ];

      const content = htpasswdSyncEngine.buildHtpasswdContent(users);

      expect(content).toContain('alice:{SHA}hash1');
      expect(content).not.toContain('bob:');
      expect(content).toContain('charlie:{SHA}hash3');
    });

    it('should handle empty user list', () => {
      const content = htpasswdSyncEngine.buildHtpasswdContent([]);

      expect(content).toContain('Generated by Konnect');
      expect(content).not.toContain(':');
    });
  });

  describe('validateHtpasswdContent', () => {
    it('should validate correct content', () => {
      const content = 'alice:{SHA}hash1\nbob:{SHA}hash2\n';
      const expectedUsers = [
        { svn_username: 'alice' },
        { svn_username: 'bob' }
      ];

      const result = htpasswdSyncEngine.validateHtpasswdContent(content, expectedUsers);

      expect(result.valid).toBe(true);
      expect(result.errors).toHaveLength(0);
    });

    it('should detect missing users', () => {
      const content = 'alice:{SHA}hash1\n';
      const expectedUsers = [
        { svn_username: 'alice' },
        { svn_username: 'bob' }
      ];

      const result = htpasswdSyncEngine.validateHtpasswdContent(content, expectedUsers);

      expect(result.valid).toBe(false);
      expect(result.errors).toContain('Missing user: bob');
    });

    it('should detect invalid format', () => {
      const content = 'invalid_format\nalice:{SHA}hash1\n';
      const expectedUsers = [{ svn_username: 'alice' }];

      const result = htpasswdSyncEngine.validateHtpasswdContent(content, expectedUsers);

      expect(result.valid).toBe(false);
      expect(result.errors.length).toBeGreaterThan(0);
    });

    it('should handle comments', () => {
      const content = '# Comment\nalice:{SHA}hash1\nbob:{SHA}hash2\n';
      const expectedUsers = [
        { svn_username: 'alice' },
        { svn_username: 'bob' }
      ];

      const result = htpasswdSyncEngine.validateHtpasswdContent(content, expectedUsers);

      expect(result.valid).toBe(true);
    });

    it('should warn about unexpected users', () => {
      const content = 'alice:{SHA}hash1\nbob:{SHA}hash2\ncharlie:{SHA}hash3\n';
      const expectedUsers = [
        { svn_username: 'alice' },
        { svn_username: 'bob' }
      ];

      const result = htpasswdSyncEngine.validateHtpasswdContent(content, expectedUsers);

      // Valid but has unexpected users (logged as warning)
      expect(result.valid).toBe(true);
    });

    it('should handle missing password hash', () => {
      const content = 'alice\n';
      const expectedUsers = [{ svn_username: 'alice' }];

      const result = htpasswdSyncEngine.validateHtpasswdContent(content, expectedUsers);

      expect(result.valid).toBe(false);
      expect(result.errors.length).toBeGreaterThan(0);
    });
  });

  describe('generateApacheMD5', () => {
    it('should generate consistent hashes for same password', () => {
      const password = 'testpassword123';

      const hash1 = htpasswdSyncEngine.generateApacheMD5(password);
      const hash2 = htpasswdSyncEngine.generateApacheMD5(password);

      // Both should start with {SHA}
      expect(hash1).toMatch(/^\{SHA\}/);
      expect(hash2).toMatch(/^\{SHA\}/);
    });

    it('should generate different hashes for different passwords', () => {
      const hash1 = htpasswdSyncEngine.generateApacheMD5('password1');
      const hash2 = htpasswdSyncEngine.generateApacheMD5('password2');

      expect(hash1).not.toBe(hash2);
    });

    it('should generate base64-encoded SHA hashes', () => {
      const hash = htpasswdSyncEngine.generateApacheMD5('testpassword');

      // Should match {SHA}base64pattern
      expect(hash).toMatch(/^\{SHA\}[A-Za-z0-9+/=]+$/);
    });
  });
});
