export const queryKeys={
  activity:{
    all:['activity'],
    list:(params={})=>[
      'activity',
      params,
    ],
  },

  dashboard:{
    stats:['dashboard','stats'],
    activity:(limit)=>[
      'dashboard',
      'activity',
      limit,
    ],
    commits:(days)=>[
      'dashboard',
      'commits',
      days,
    ],
  },

  groups:{
    all:['groups'],
    list:(params={})=>[
      'groups',
      'list',
      params,
    ],
    detail:(id)=>[
      'groups',
      id,
    ],
    members:(id)=>[
      'groups',
      id,
      'members',
    ],
  },

  hooks:{
    templates:['hook-templates'],
    byRepo:(repoId)=>[
      'hooks',
      repoId,
    ],
    single:(repoId,hookName)=>[
      'hooks',
      repoId,
      hookName,
    ],
  },

  auditLogs:{
    all:['audit-logs'],
    list:(params={})=>[
      'audit-logs',
      params,
    ],
    commits:(params={})=>[
      'commit-logs',
      params,
    ],
  },

  repositories:{
    all:['repositories'],
    list:(params={})=>[
      'repositories',
      params,
    ],
    detail:(id)=>[
      'repositories',
      id,
    ],
    activity:(repoId,params={})=>[
      'repositories',
      repoId,
      'activity',
      params,
    ],
    files:(repoId)=>[
      'repo-tree',
      repoId,
    ],
    fileContent:(repoId,path)=>[
      'file-content',
      repoId,
      path,
    ],
    branches:(repoId)=>[
      'branches',
      repoId,
    ],
    tags:(repoId)=>[
      'tags',
      repoId,
    ],
    commits:(repoId,params={})=>[
      'repo-commits',
      repoId,
      params,
    ],
  },

  users:{
    all:['users'],
    list:(params={})=>[
      'users',
      'list',
      params,
    ],
    detail:(id)=>[
      'users',
      'detail',
      String(id),
    ],
    me:['users','me'],
  },

  permissions:{
    byRepo:(repoId)=>[
      'permissions',
      repoId,
    ],
  },

  notifications:{
    all:['notifications'],
    list:(params={})=>[
      'notifications',
      params,
    ],
    count:['notifications-count'],
  },
}
